#!/bin/bash

# This script wrap the git command with expect, use environment AZ_USER and AZ_TOKEN to interact with Azure git
# export AZ_USER='[username]'
# export AZ_TOKEN='[your_token]'


# Use a here document with expect
/usr/bin/expect <<EOF
# Start the provided command with all arguments
set timeout -1
spawn $*

# Handle prompts for username and password
expect {
    -re "Username.*quanta01.visualstudio.com.*:" {
        send "${AZ_USER}\r"
        expect {
            -re "Password.*quanta01.visualstudio.com.*:" {
                send "${AZ_TOKEN}\r"
                exp_continue
            }
        }
    }

    "Username for 'https://github.com':" {
        send "${GIT_USER}\r"
        exp_continue
    }
    "Password for*github.com':" {
        send "${GIT_TOKEN}\r"
        exp_continue
    }
}
EOF

