#!/bin/bash

# This script wrap the git command with expect, use environment AZ_USER and AZ_TOKEN to interact with Azure git
# export AZ_USER='[username]'
# export AZ=TOKEN='[your_token]''

/usr/bin/expect <<EOF
spawn $*
expect {
"Username*quanta01.visualstudio.com:" { send "$AZ_USER\r"; exp_continue }
"Password*quanta01.visualstudio.com:" { send "$AZ_TOKEN\r"; exp_continue }
}
EOF